Repository Software-Engineering-LNU/Software-Engineering-Project, pull requests merged in 2022-10, with the labels that each got.

#24 Task 13 - Created file with software requirements specification
  Documents/Software Requirements Specification.pdf
Labels: documentation, Medium priority

#28 Task 20 - Implement database records generation
  EmployeestSeedConsoleApp.sln
  EmployeestSeedConsoleApp/Data/EmployeestDbContext.cs
  EmployeestSeedConsoleApp/Data/EmployeestSeedData.cs
  EmployeestSeedConsoleApp/Data/IUnitOfWork.cs
  EmployeestSeedConsoleApp/Data/UnitOfWork.cs
  EmployeestSeedConsoleApp/EmployeestSeedConsoleApp.csproj
  EmployeestSeedConsoleApp/Entities/Event.cs
  EmployeestSeedConsoleApp/Entities/EventMember.cs
  EmployeestSeedConsoleApp/Entities/Permission.cs
  EmployeestSeedConsoleApp/Entities/Position.cs
  EmployeestSeedConsoleApp/Entities/PositionPermission.cs
  EmployeestSeedConsoleApp/Entities/Project.cs
  EmployeestSeedConsoleApp/Entities/ProjectMember.cs
  EmployeestSeedConsoleApp/Entities/Task.cs
  EmployeestSeedConsoleApp/Entities/Team.cs
  EmployeestSeedConsoleApp/Entities/TeamMember.cs
  EmployeestSeedConsoleApp/Entities/User.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/EventFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/EventMemberFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/PermissionFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/PositionFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/PositionPermissionFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/ProjectFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/ProjectMembersFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/TaskFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/TeamFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/TeamMemberFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Implementation/UserFactory.cs
  EmployeestSeedConsoleApp/EntityFactories/Interfaces/IDbEntityFactory.cs
  EmployeestSeedConsoleApp/Program.cs
Labels: Feature, TechTask, High priority

#36 Fix 20 - Refactor UserFactory class
  EmployeestSeedConsoleApp/EntityFactories/Implementation/UserFactory.cs
Labels: Bug

#54 Task 32 - Implement main GUI template
  Software-Engineering-Project/Assets/AvArr.png
  Software-Engineering-Project/Assets/Avatar.png
  Software-Engineering-Project/Assets/BottomArrow.png
  Software-Engineering-Project/Assets/ChangeSchedule.png
  Software-Engineering-Project/Assets/Chat.png
  Software-Engineering-Project/Assets/Employees.png
  Software-Engineering-Project/Assets/Home.png
  Software-Engineering-Project/Assets/NewProject.png
  Software-Engineering-Project/Assets/Notification2.png
  Software-Engineering-Project/Assets/Notifications.png
  Software-Engineering-Project/Assets/Project.png
  Software-Engineering-Project/Assets/Search.png
  Software-Engineering-Project/Assets/Settings.png
  Software-Engineering-Project/Assets/Statistics.png
  Software-Engineering-Project/Assets/Team.png
  Software-Engineering-Project/Assets/mini_logo.png
  Software-Engineering-Project/Assets/schedule.png
  Software-Engineering-Project/MainWindow.xaml
  Software-Engineering-Project/MainWindow.xaml.cs
  Software-Engineering-Project/NavButton.cs
  Software-Engineering-Project/Software-Engineering-Project.csproj
  Software-Engineering-Project/Themes/Generic.xaml
Labels: Feature, High priority

#57 Fix 32 - Fix full screen state
  Software-Engineering-Project/MainWindow.xaml
Labels: Bug, High priority
